import MathsModule from "./app";

export let {
  abs,
  add,
  arccosInDeg,
  arcsinInDeg,
  arctanInDeg,
  combination,
  common_factor,
  cosecInDegree,
  cosInDegree,
  cotInDegree,
  decimalPlaces,
  determinantThreeByThree,
  determinantTwoByTwo,
  distBtwTwoPlaces,
  factorial,
  factors,
  floor,
  getMean,
  getMedian,
  getMode,
  HCF,
  LCM,
  permutation,
  radToDeg,
  range,
  sinInDegree,
  significantFigure,
  simuThreeVar,
  simuTwoVar,
  sort,
  standardDeviation,
  tanInDegree,
  degToRad,
  variance,
} = new MathsModule();
